### PR TITLE
[python38-nox] Add test to python 3.7 and 3.8 explicitly

### PR DESCRIPTION
**Pull request by matheusbrat**
This PR includes a few changes:
- Add python 3.8 support on nox
- Add python 3.8 on .travis.yml
- Remove python 3.6 and older from setup.py classifiers  
- Update README to include Python 3.8 support

What do you think?

### CODE REVIEW

**Comment by untitaker** [comment]
Thanks! A couple of notes:

* I don't think we need to run the lint job multiple times.
* I really do not want to drop Python 2 or pypy support (both are no longer tested in your pr)
* I noticed that on master we also did not test with pypy, but that's a mistake

**Comment by untitaker** [comment]
@x-warrior I would copypaste the setup from here: https://github.com/getsentry/sentry-python/blob/master/.travis.yml

**Comment by matheusbrat** [comment]
@untitaker I'm not sure if that would work to be honest. If we describe the python versions in travis fashion it will fail installing nox for py2.7 and pypy as:

> Nox no longer supports Python 2.7. You can still create and run Python 2.7 sessions, but Nox itself must be installed using Python 3.5+.

That happens because when we have python 2.7 it will try to install nox with it and that will fail. Therefore we always need to install nox with python 3 which doesn't seem doable. 

The approach I'm trying now is to install all pythons manually.

**Comment by matheusbrat** [comment]
@untitaker I managed to install all python versions manually and simply use nox to test it. We are still missing pypy but at least it is a bit better than it was. What do you think?
Do you want me to squash the commits or something like this to avoid polluting the history?

**Review by untitaker — APPROVED** [review]

**Comment by untitaker** [comment]
I squash-merged into master, thanks!

I hope to get pypy running soon

**Pull request merged**
